update: added checked for secure boot

diff --git a/ryzenadj_helper_installer b/ryzenadj_helper_installer
--- a/ryzenadj_helper_installer
+++ b/ryzenadj_helper_installer
@@ -45,6 +45,18 @@ else
                 arg2_info=" ${translations[(default 20)]}"
             fi
 
+            IFS=' ' read -r -a SECUREBOOT_STATUS < <(mokutil --sb-state)
+            CHECK_DKMS_SIGN=$(mokutil --list-enrolled | grep -i dkms)
+            if [[ -f /var/lib/dkms/mok.pub ]] && [[ ${SECUREBOOT_STATUS[1]} == enabled ]] && [[ -z $CHECK_DKMS_SIGN ]] ; then
+                echo "${translations[Secureboot is enabled in the BIOS, before using this script you need to import the key for signing dkms modules for ryzen_smu in mokutil]}"
+                mokutil --import /var/lib/dkms/mok.pub
+                echo "${translations[Reboot your device, import the key and run the script again]}"
+                sleep 5 && exit 0
+            elif [[ ! -f /var/lib/dkms/mok.pub ]] && [[ ${SECUREBOOT_STATUS[1]} == enabled ]] && [[ -z $CHECK_DKMS_KEY ]] ; then
+                echo "${translations[Secureboot is enabled in BIOS, /var/lib/dkms/mok.pub for signing dkms modules for ryzen_smu is missing, disable secureboot or add the key for signing dkms modules to mokutil]}"
+                sleep 5 && exit 1
+            fi
+
             echo "${translations[Enter the maximum TDP of the processor from the power cable in watts]}$arg1_info:"
             read -r arg1
             echo "${translations[Enter the maximum TDP of the processor from the battery in watts]}$arg2_info:"
@@ -53,6 +65,7 @@ else
             read -r arg3
             echo "${translations[Enter the maximum allowed APU temperature in Celsius (default 70)]}:"
             read -r arg4
+
             if [[ $(</sys/class/dmi/id/product_version) == ThinkBook\ 1*\ G6+\ AHP ]] ; then
                 echo "${translations[Enter the maximum TDP of the processor from the power cable in watts from a weak charge (default 25)]}:"
                 read -r arg5
@@ -60,15 +73,13 @@ else
                 echo "${translations[Available profiles: performance, balanced, low-power (balanced by default)]}:"
                 read -r arg6
                 if [[ -n $arg6 ]] && [[ ! $arg6 =~ (performance|balanced|low-power) ]] ; then
-                    echo "${translations[Incorrect profile (vantage) selected, default profile will be used]}"
-                    sleep 5
-                    unset arg6
+                    echo "${translations[Invalid argument used, exiting in 3 seconds]}"
+                    sleep 3 && exit 1
                 fi
             fi
-            IFS=' ' read -r -a SECUREBOOT_STATUS < <(mokutil --sb-state)
-            if [[ ${SECUREBOOT_STATUS[1]} != "enabled" ]] ; then
-                echo "${translations[Secureboot is disabled in the system, install the ryzen_smu kernel module?]}"
-                echo "${translations[May improve compatibility with ryzenadj]}"
+
+            if [[ -z $CHECK_DKMS_SIGN ]] ; then
+                echo "${translations[Install the ryzen_smu kernel module? May improve compatibility with ryzenadj]}"
                 echo "${translations[Select y/yes or n/no (default yes)]}:"
                 read -r arg7
                 if [[ -n $arg7 ]] && [[ ! $arg7 =~ (y|yes|n|no) ]] ; then
@@ -76,10 +87,12 @@ else
                     sleep 3 && exit 1
                 fi
             fi
+
             echo "${translations[Add a timer to the system so that the device turns off automatically during prolonged sleep]}"
             echo "${translations[Similar to hibernation, but without saving the current session]}"
             echo "${translations[Select y/yes or n/no (default yes)]}:"
             read -r arg8
+
             if [[ -n $arg8 ]] && [[ ! $arg8 =~ (y|yes|n|no) ]] ; then
                 echo "${translations[Invalid argument used, exiting in 3 seconds]}"
                 sleep 3 && exit 1
