refactoring code

diff --git a/ryzenadj_helper_installer b/ryzenadj_helper_installer
--- a/ryzenadj_helper_installer
+++ b/ryzenadj_helper_installer
@@ -37,7 +37,7 @@ else
 
     custom_args_ryzenadj() {
             # Honor BMH-WCX9
-            if [[ $(</sys/class/dmi/id/product_version) == M1060 ]] ; then
+            if [[ $(</sys/class/dmi/id/product_version) == "M1060" ]] ; then
                 arg1_info=" (${translations[default]} 25)"
                 arg2_info=" (${translations[default]} 15)"
             # Thinkbook G6+ AHP
@@ -48,15 +48,17 @@ else
 
             IFS=' ' read -r -a SECUREBOOT_STATUS < <(mokutil --sb-state)
             CHECK_DKMS_SIGN=$(mokutil --list-enrolled | grep -i dkms)
-            if [[ -f /var/lib/dkms/mok.pub ]] && [[ ${SECUREBOOT_STATUS[1]} == enabled ]] && [[ -z $CHECK_DKMS_SIGN ]] ; then
-                echo "${translations[Secureboot is enabled in the BIOS, before using this script you need to import the key for signing dkms modules for ryzen_smu in mokutil]}"
-                echo "${translations[You can use any password]}"
-                mokutil --import /var/lib/dkms/mok.pub
-                echo "${translations[Reboot your device, import the key and run the script again]}"
-                sleep 3 && exit 0
-            elif [[ ! -f /var/lib/dkms/mok.pub ]] && [[ ${SECUREBOOT_STATUS[1]} == enabled ]] && [[ -z $CHECK_DKMS_KEY ]] ; then
-                echo "${translations[Secureboot is enabled in BIOS, /var/lib/dkms/mok.pub for signing dkms modules for ryzen_smu is missing, disable secureboot or add the key for signing dkms modules to mokutil]}"
-                sleep 3 && exit 1
+            if [[ ${SECUREBOOT_STATUS[1]} == "enabled" ]] && [[ -z $CHECK_DKMS_SIGN ]] ; then
+                if [[ -f /var/lib/dkms/mok.pub ]] ; then
+                    echo "${translations[Secureboot is enabled in the BIOS, before using this script you need to import the key for signing dkms modules for ryzen_smu in mokutil]}"
+                    echo "${translations[You can use any password]}"
+                    mokutil --import /var/lib/dkms/mok.pub
+                    echo "${translations[Reboot your device, import the key and run the script again]}"
+                    sleep 3 && exit 0
+                else
+                    echo "${translations[Secureboot is enabled in BIOS, /var/lib/dkms/mok.pub for signing dkms modules for ryzen_smu is missing, disable secureboot or add the key for signing dkms modules to mokutil]}"
+                    sleep 3 && exit 1
+                fi
             fi
 
             echo "${translations[Enter the maximum TDP of the processor from the power cable in watts]}$arg1_info:"
@@ -64,16 +66,16 @@ else
             echo "${translations[Enter the maximum TDP of the processor from the battery in watts]}$arg2_info:"
             read -r arg2
             echo "${translations[Enter the maximum allowed CPU temperature in Celsius (default 70)]}:"
-            read -r arg3 && [[ -z $arg3 ]] && arg3=70
+            read -r arg3 && [[ -z $arg3 ]] && arg3="70"
             echo "${translations[Enter the maximum allowed APU temperature in Celsius (default 70)]}:"
-            read -r arg4 && [[ -z $arg4 ]] && arg4=70
+            read -r arg4 && [[ -z $arg4 ]] && arg4="70"
 
             if [[ $(</sys/class/dmi/id/product_version) == ThinkBook\ 1*\ G6+\ AHP ]] ; then
                 echo "${translations[Enter the maximum TDP of the processor from the power cable in watts from a weak charge (default 25)]}:"
-                read -r arg5 && [[ -z $arg5 ]] && arg5=25
+                read -r arg5 && [[ -z $arg5 ]] && arg5="25"
                 echo "${translations[Enter which profile to use (vantage) after reboot or shutdown, this is necessary for the second system, for example Windows]}"
                 echo "${translations[Available profiles: performance, balanced, low-power (balanced by default)]}:"
-                read -r arg6 && [[ -z $arg6 ]] && arg6=balanced
+                read -r arg6 && [[ -z $arg6 ]] && arg6="balanced"
                 if [[ -n $arg6 ]] && [[ ! $arg6 =~ ^(performance|balanced|low-power)$ ]] ; then
                     echo "${translations[Invalid argument used, exiting in 3 seconds]}"
                     sleep 3 && exit 1
@@ -83,7 +85,7 @@ else
             if [[ -z $CHECK_DKMS_SIGN ]] ; then
                 echo "${translations[Install the ryzen_smu kernel module? May improve compatibility with ryzenadj]}"
                 echo "${translations[Select y/yes or n/no (default no)]}:"
-                read -r arg7 && [[ -z $arg7 ]] && arg7=no
+                read -r arg7 && [[ -z $arg7 ]] && arg7="no"
                 if [[ -n $arg7 ]] && [[ ! $arg7 =~ ^(y|yes|n|no)$ ]] ; then
                     echo "${translations[Invalid argument used, exiting in 3 seconds]}"
                     sleep 3 && exit 1
@@ -93,7 +95,7 @@ else
             echo "${translations[Add rtcwake to the system so that the device automatically turns off after a long sleep]}"
             echo "${translations[Similar to hibernation, but without saving the current session]}"
             echo "${translations[Select y/yes or n/no (default yes)]}:"
-            read -r arg8 && [[ -z $arg8 ]] && arg8=yes
+            read -r arg8 && [[ -z $arg8 ]] && arg8="yes"
 
             if [[ -n $arg8 ]] && [[ ! $arg8 =~ ^(y|yes|n|no)$ ]] ; then
                 echo "${translations[Invalid argument used, exiting in 3 seconds]}"
@@ -101,7 +103,7 @@ else
             fi
             if [[ $arg8 =~ ^(y|yes)$ ]] ; then
                 echo "${translations[How long to turn off the device during long sleep in minutes (default 180)]}:"
-                read -r arg9 && [[ -z $arg9 ]] && arg9=180
+                read -r arg9 && [[ -z $arg9 ]] && arg9="180"
                 arg9=$(( arg9 * 60 ))
             fi
     }
@@ -158,8 +160,8 @@ EOF
 
     ryzenadj_helper_install() {
         if [[ $(</sys/class/dmi/id/product_version) == ThinkBook\ 1*\ G6+\ AHP ]] ; then
-            [[ -z $arg1 ]] && arg1=35
-            [[ -z $arg2 ]] && arg2=20
+            [[ -z $arg1 ]] && arg1="35"
+            [[ -z $arg2 ]] && arg2="20"
             cat << EOF > $INSTALL_DIR/bin/ryzenadj_helper
 #!/usr/bin/env bash
 
@@ -202,9 +204,9 @@ EOF
 
         systemctl enable --now ryzenadj_helper_off.service 2>/dev/null
         else
-            if [[ $(</sys/class/dmi/id/product_version) == M1060 ]] ; then
-                [[ -z $arg1 ]] && arg1=25
-                [[ -z $arg2 ]] && arg2=15
+            if [[ $(</sys/class/dmi/id/product_version) == "M1060" ]] ; then
+                [[ -z $arg1 ]] && arg1="25"
+                [[ -z $arg2 ]] && arg2="15"
             fi
             [[ -n $arg1 ]] && arg1="-a ${arg1}000 -b ${arg1}000 -c ${arg1}000"
             [[ -n $arg2 ]] && arg2="-b ${arg2}000 -b ${arg2}000 -c ${arg2}000"
@@ -314,7 +316,7 @@ EOF
             custom_args_ryzenadj
             ryzenadj_helper_full_uninstall
             ryzenadj_install
-            [[ ! $arg7 =~ ^(n|no)$ ]] || [[ -n $CHECK_DKMS_SIGN ]] && ryzen_smu_install
+            [[ ! $arg7 =~ ^(n|no)$ ]] && ryzen_smu_install
             ryzenadj_helper_install
             [[ ! $arg8 =~ ^(n|no)$ ]] && suspend_timer_install
         ;;
